flags: {}
extra-package-dbs: []
packages:
- '.'
system-ghc: false
extra-deps:
- QuickCheck-2.8.2
- StateVar-1.1.0.4
- adjunctions-4.3
- arithmoi-0.4.2.0
- base-orphans-0.5.4
- bifunctors-5.3
- comonad-5
- contravariant-1.4
- data-default-class-0.1.0
- distributive-0.5.0.2
- dlist-0.7.1.2
- dlist-instances-0.1
- exceptions-0.8.2.1
- free-4.12.4
- hashable-1.2.4.0
- kan-extensions-5.0.1
- keys-3.11
- mono-traversable-0.10.2
- mtl-2.2.1
- mwc-random-0.13.4.0
- pointed-5
- prelude-extras-0.4.0.3
- primitive-0.6.1.0
- profunctors-5.2
- random-1.1
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- safe-0.3.9
- semigroupoids-5.0.1
- semigroups-0.18.1
- split-0.2.3.1
- stm-2.4.4.1
- tagged-0.8.4
- text-1.2.2.1
- tf-random-0.5
- transformers-compat-0.5.1.4
- unordered-containers-0.2.7.0
- vector-0.11.0.0
- vector-algorithms-0.7.0.1
- vector-instances-3.3.1
- void-0.7.1
compiler-check: newer-minor
resolver: ghc-8.0.1
